name: Pulumi - Check

on:
  pull_request:
    branches:
      - main

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        id: checkout
        uses: actions/checkout@v2

      - name: Install Node.JS
        id: install_node
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        id: install_deps
        run: npm install

      - name: Configure AWS Credentials
        id: aws_credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{vars.AWS_REGION}}

      - name: Run Pulumi Preview
        id: pulumi_preview
        uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: patriciasegantine/stage
          cloud-url: s3://patriciasegantine-pulumi-state
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          WS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION}: ${{vars.AWS_REGION}}
          PULUMI_CONFIG_PASSPHRASE: ''
